# Generated by Django 4.1.3 on 2022-11-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_post_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAbsen', models.TextField(max_length=50)),
                ('keterangan', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='beritaAcara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAcara', models.TextField(max_length=50)),
                ('pertemuan', models.TextField(max_length=5)),
                ('tanggal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.TextField(max_length=15)),
                ('namaDosen', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFoto', models.IntegerField()),
                ('namaFoto', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='golongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGol', models.TextField(max_length=2)),
                ('namaGol', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJadwal', models.TextField(max_length=50)),
                ('ruangan', models.TextField(max_length=5)),
                ('hari', models.TextField(max_length=30)),
                ('jamMulai', models.IntegerField()),
                ('jamSelesai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeMK', models.TextField(max_length=10)),
                ('mataKuliah', models.TextField(max_length=50)),
                ('sks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nim', models.CharField(max_length=9)),
                ('Foto', models.ImageField(upload_to='')),
                ('Nama', models.CharField(max_length=20)),
                ('Kelas', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Internasional', 'Internasional')])),
                ('Semester', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')])),
                ('Telepon', models.CharField(max_length=14)),
                ('Alamat', models.TextField(max_length=20)),
                ('Jenis_Kelamin', models.TextField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')])),
            ],
        ),
    ]
