# Generated by Django 4.1.3 on 2022-11-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_absensi_beritaacara_dosen_foto_golongan_jadwal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='idAbsen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beritaacara',
            name='idAcara',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beritaacara',
            name='pertemuan',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='namaDosen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='foto',
            name='namaFoto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='idGol',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='golongan',
            name='namaGol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='idJadwal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='ruangan',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='kodeMK',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='mataKuliah',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterModelTable(
            name='dosen',
            table='admins_dosen',
        ),
        migrations.AlterModelTable(
            name='member',
            table='admins_member',
        ),
    ]
