# Generated by Django 3.2.16 on 2022-11-29 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20221129_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='matkul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.matkul'),
        ),
    ]
