# Generated by Django 3.2.16 on 2022-11-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_jadwal_matkul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkul',
            name='kodeMK',
            field=models.CharField(max_length=20),
        ),
    ]
