# Generated by Django 3.2.16 on 2022-12-06 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_matkul_kodemk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='foto',
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.mahasiswa')),
            ],
            options={
                'db_table': 'tb_dataset',
            },
        ),
    ]
