# Generated by Django 3.2.16 on 2022-12-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_auto_20221206_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='third',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
