# Generated by Django 3.2.16 on 2022-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20221206_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='first',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='second',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='third',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
