# Generated by Django 3.2.16 on 2022-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_auto_20221206_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='foto',
        ),
        migrations.AddField(
            model_name='dataset',
            name='foto1',
            field=models.FileField(blank=True, null=True, upload_to='dataset/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='foto2',
            field=models.FileField(blank=True, null=True, upload_to='dataset/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='foto3',
            field=models.FileField(blank=True, null=True, upload_to='dataset/'),
        ),
    ]
